name: Debug Input

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Select log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  show-input:
    runs-on: ubuntu-latest
    steps:
      - name: Show selected log level
        run: echo "Log Level is: ${{ github.event.inputs.logLevel }}"
